export const COLORS = {
  light: {
    bg: '#fafafa',
    bgSecondary: '#f5f5f5',
    card: '#ffffff',
    border: '#e0e0e0',
    borderLight: '#eeeeee',
    text: '#1a1a1a',
    textSecondary: '#666666',
    textTertiary: '#999999',
    userMessageBg: '#4f46e5',
    userMessageText: '#ffffff',
    errorBg: '#fef2f2',
    errorBorder: '#fecaca',
    errorText: '#991b1b',
    modelBadgeBg: '#f5f5f5',
    modelBadgeBorder: '#d4d4d4',
    modelBadgeText: '#525252',
    sourceBadgeBg: '#f0fdf4',
    sourceBadgeBorder: '#86efac',
    sourceBadgeText: '#15803d',
  },
  dark: {
    bg: '#0a0a0a',
    bgSecondary: '#141414',
    card: '#1a1a1a',
    border: '#262626',
    borderLight: '#2a2a2a',
    text: '#e5e5e5',
    textSecondary: '#a3a3a3',
    textTertiary: '#737373',
    userMessageBg: '#6366f1',
    userMessageText: '#ffffff',
    errorBg: '#1c1917',
    errorBorder: '#292524',
    errorText: '#fca5a5',
    modelBadgeBg: '#1a1a1a',
    modelBadgeBorder: '#3a3a3a',
    modelBadgeText: '#d4d4d4',
    sourceBadgeBg: '#14532d',
    sourceBadgeBorder: '#22c55e',
    sourceBadgeText: '#86efac',
  },
};

export const PT_BR = {
  header: {
    chat: 'Chat',
    upload: 'Upload',
    toggleTheme: 'Alternar tema',
  },
  chat: {
    loadingModels: 'Carregando modelos...',
    startConversation: 'Inicie uma conversa',
    askQuestion: 'Comece perguntando sobre os documentos ou tópicos que deseja explorar.',
    inputPlaceholder: 'Faça uma pergunta...',
    inputWaiting: 'Aguardando resposta...',
    thinking: 'Pensando...',
    sendMessage: 'Enviar mensagem (Enter)',
  },
  upload: {
    title: 'Carregar documentos',
    subtitle: 'Envie seus documentos para começar',
    dragText: 'Arraste arquivos aqui ou clique para selecionar',
    supportedFormats: 'Formatos suportados: PDF, TXT, DOCX',
    uploading: 'Enviando...',
    uploadButton: 'Escolher arquivo',
    successTitle: 'Upload realizado com sucesso!',
    documentId: 'ID do documento',
    chunksCount: 'Chunks processados',
    startChat: 'Começar chat',
    uploadAnother: 'Enviar outro arquivo',
    errorTitle: 'Erro ao enviar',
    emptyFile: 'Por favor, selecione um arquivo',
    errorUploading: 'Erro ao enviar arquivo',
  },
};
